[package]
name = "ori-core"
version = "0.1.0-alpha.1"
edition = "2021"
description = "Core library for Ori, a declarative UI framework for Rust."
keywords = ["gui", "graphics", "reactive", "native"]
categories = ["gui", "graphics"]
repository = "https://github.com/ChangeCaps/ori"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ori-graphics = { path = "../ori-graphics", version = "0.1.0-alpha.1" }
ori-macro = { path = "../ori-macro", version = "0.1.0-alpha.1" }
ori-reactive = { path = "../ori-reactive", version = "0.1.0-alpha.1" }

deref-derive = "0.1"
glam = "0.24"
lazy_static = "1.4"
nohash-hasher = "0.2"
parking_lot = "0.12"
pest = "2.5"
pest_derive = "2.5"
serde = { version = "1.0", features = ["derive"], optional = true }
smallvec = { version = "1.10", features = ["union", "const_generics", "const_new"] }
seahash = "4.1"
smol_str = "0.2"
tracing = { version = "0.1", default-features = false, features = ["attributes"] }
uuid = { version = "1.3", features = ["v4"] }

[features]
default = []
serde = ["dep:serde", "smol_str/serde", "smallvec/serde"]
