[package]
name = "ori-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ori-macro = { path = "../ori-macro", version = "0.1.0-alpha.1" }

bitflags = "2.4"
crossbeam-channel = "0.5"
etagere = "0.2"
fontdb = "0.14"
fontdue = "0.7"
seahash = "4.1"

[dependencies.image]
version = "0.24"
default-features = false
optional = true
features = [
    "gif",
    "jpeg",
    "png",
    "pnm",
    "tga",
    "webp",
    "bmp", 
]

[dependencies.tracing]
version = "0.1"
default-features = false
optional = true

[features]
default = []
image = ["dep:image"]
tracing = ["dep:tracing"]
