[package]
name = "ori"
version = "0.1.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*"]

[dependencies]
# Internal dependencies
ori-core = { path = "crates/ori-core", version = "0.1.0-alpha.1" }

# Optional dependencies
ori-wgpu = { path = "crates/ori-wgpu", version = "0.1.0-alpha.1", optional = true }

[dev-dependencies.ori]
path = "."
version = "0.1.0-alpha.1"
features = ["image", "tracing"]


[features]
default = ["wgpu"]
image = ["ori-core/image"]
tracing = ["ori-core/tracing"]

# Backend features
wgpu = ["dep:ori-wgpu"]

[profile.dev]
debug = false
