[package]
name = "ori"
description = "A declarative, data-driven 2D ui framework"
keywords = ["ui", "gui", "2d", "declarative", "data-driven"]
categories = ["ui", "graphics"]
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*"]

[workspace.package]
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["Ori Contributors"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
ori-core = { path = "crates/ori-core", version = "0.1.0-alpha.1" }
ori-font-awesome = { path = "crates/ori-font-awesome", version = "0.1.0-alpha.1" }
ori-glow = { path = "crates/ori-glow", version = "0.1.0-alpha.1" }
ori-macro = { path = "crates/ori-macro", version = "0.1.0-alpha.1" }
ori-wgpu = { path = "crates/ori-wgpu", version = "0.1.0-alpha.1" }
ori-winit = { path = "crates/ori-winit", version = "0.1.0-alpha.1" }

[dependencies]
# Internal dependencies
ori-core = { workspace = true }
ori-macro = { workspace = true }

# Optional dependencies
ori-font-awesome = { workspace = true, optional = true }

# Backend dependencies
ori-winit = { workspace = true, optional = true }

[dev-dependencies.ori]
path = "."
version = "0.1.0-alpha.1"
features = ["font-awesome", "image", "tracing"]

[features]
default = ["winit", "glow", "x11"]
font-awesome = ["dep:ori-font-awesome"]
image = ["ori-core/image"]
tracing = ["ori-core/tracing", "ori-winit/tracing"]

# All features
full = ["font-awesome", "image", "tracing"]

# Backend features
winit = ["dep:ori-winit"]
x11 = ["ori-winit?/x11"]
wayland = ["ori-winit?/wayland"]
glow = ["ori-winit?/glow"]
wgpu = ["ori-winit?/wgpu"]

[profile.dev]
debug = "limited"
opt-level = 1
overflow-checks = false
