[package]
name = "ori"
version = "0.1.0-alpha.1"
edition = "2021"
description = "A declarative, data-driven 2D ui framework"
keywords = ["ui", "gui", "2d", "declarative", "data-driven"]
categories = ["ui", "graphics"]
authors = ["Ori Contributors"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*"]

[dependencies]
# Internal dependencies
ori-core = { path = "crates/ori-core", version = "0.1.0-alpha.1" }

# Optional dependencies
ori-font-awesome = { path = "crates/ori-font-awesome", version = "0.1.0-alpha.1", optional = true }

# Backend dependencies
ori-wgpu = { path = "crates/ori-wgpu", version = "0.1.0-alpha.1", optional = true }

[dev-dependencies.ori]
path = "."
version = "0.1.0-alpha.1"
features = ["font-awesome", "image", "tracing"]

[features]
default = ["wgpu"]
font-awesome = ["dep:ori-font-awesome"]
image = ["ori-core/image"]
tracing = ["ori-core/tracing", "ori-wgpu/tracing"]

# All features
full = ["font-awesome", "image", "tracing"]

# Backend features
wgpu = ["dep:ori-wgpu"]

[profile.dev]
debug = false
