[package]
name = "ori"
version = "0.1.0-alpha.1"
edition = "2021"
description = "A declarative ui framework for Rust"
keywords = ["gui", "graphics", "reactive", "native"]
categories = ["gui", "graphics"]
repository = "https://github.com/ChangeCaps/ori"
readme = "README.md"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*"]

[dependencies]
ori-core = { path = "crates/ori-core", version = "0.1.0-alpha.0" }
ori-macro = { path = "crates/ori-macro", version = "0.1.0-alpha.0" }
ori-graphics = { path = "crates/ori-graphics", version = "0.1.0-alpha.0" }
ori-wgpu = { path = "crates/ori-wgpu", version = "0.1.0-alpha.0", optional = true }
ori-winit = { path = "crates/ori-winit", version = "0.1.0-alpha.0", optional = true }

[features]
default = ["winit", "wgpu"]
wgpu = ["ori-wgpu", "ori-winit/wgpu"]
winit = ["ori-winit"]

[profile.dev]
debug = false
opt-level = 1
