[package]
name = "ily"
version = "0.1.0"
edition = "2021"
description = "A reactive ui framework for Rust"
keywords = ["ui", "gui", "graphics", "wgpu", "winit", "reactive", "native"]
categories = ["gui", "graphics"]
readme = "README.md"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*"]

[dependencies]
ily-core = { path = "crates/ily-core", version = "0.1.0" }
ily-macro = { path = "crates/ily-macro", version = "0.1.0" }
ily-graphics = { path = "crates/ily-graphics", version = "0.1.0" }
ily-wgpu = { path = "crates/ily-wgpu", version = "0.1.0", optional = true }
ily-winit = { path = "crates/ily-winit", version = "0.1.0", optional = true }

[features]
default = ["winit", "wgpu"]
wgpu = ["ily-wgpu", "ily-winit/wgpu"]
winit = ["ily-winit"]

[profile.dev]
debug = false
opt-level = 1
