[package]
name = "ori-macro"
version = "0.1.0-alpha.1"
edition = "2021"
description = "Macros for Ori"
keywords = ["gui", "graphics", "reactive", "native"]
categories = ["gui", "graphics"]
repository = "https://github.com/ChangeCaps/ori"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
proc-macro-error = "1.0"
proc-macro-crate = "1.3"
quote = "1.0"
syn = "1.0"
syn-rsx = "0.9"
