[package]
name = "ori-shell"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ori-app.workspace = true
ori-core.workspace = true
ori-glow.workspace = true

[features]
default = []
x11 = ["libloading", "x11rb", "xkbcommon", "xkbcommon/x11"]
wayland = ["xkbcommon", "xkbcommon/wayland"]

[target.'cfg(target_os = "linux")'.dependencies]
libloading  = { version = "0.8",    optional = true }
xkbcommon   = { version = "0.8",    optional = true }

[target.'cfg(target_os = "linux")'.dependencies.x11rb]
version     = "0.13"
optional    = true
features    = ["render", "allow-unsafe-code", "xkb"]
