[package]
name = "suspense"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ori = { path = "../..", features = ["image"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
tokio = { version = "1", features = ["full"] }
