[package]
name = "ori-wgpu"
version = "0.1.0-alpha.1"
edition = "2021"
description = "WGPU backend for Ori"
keywords = ["gui", "graphics", "reactive", "native"]
categories = ["gui", "graphics"]
repository = "https://github.com/ChangeCaps/ori"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ori-core = { path = "../ori-core", version = "0.1.0-alpha.0" }
ori-graphics = { path = "../ori-graphics", version = "0.1.0-alpha.0" }

bytemuck = { version = "1.13", features = ["derive"] }
pollster = "0.3"
raw-window-handle = "0.5"
wgpu = "0.16"

# wait for 0.3, we need to be able to set MultisampleState::count
[dependencies.glyphon]
git = "https://github.com/grovesNL/glyphon"
rev = "80e8465"
