[package]
name = "ori-winit"
version = "0.1.0-alpha.0"
edition = "2021"
description = "Winit backend for Ori"
keywords = ["ui", "gui", "graphics", "wgpu", "winit", "reactive", "native"]
categories = ["gui", "graphics"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ori-core = { path = "../ori-core", version = "0.1.0-alpha.0" }
ori-graphics = { path = "../ori-graphics", version = "0.1.0-alpha.0" }
ori-wgpu = { path = "../ori-wgpu", version = "0.1.0-alpha.0", optional = true }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
winit = "0.28.0"

[features]
default = []
wgpu = ["ori-wgpu"]
