[package]
name = "ori-winit"
version = "0.1.0-alpha.1"
edition = "2021"
description = "Winit backend for Ori"
keywords = ["gui", "graphics", "reactive", "native"]
categories = ["gui", "graphics"]
repository = "https://github.com/ChangeCaps/ori"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ori-core = { path = "../ori-core", version = "0.1.0-alpha.0" }
ori-graphics = { path = "../ori-graphics", version = "0.1.0-alpha.0" }
ori-reactive = { path = "../ori-reactive", version = "0.1.0-alpha.0" }
ori-style = { path = "../ori-style", version = "0.1.0-alpha.0" }

ori-wgpu = { path = "../ori-wgpu", version = "0.1.0-alpha.0", optional = true }

raw-window-handle = "0.5"
seahash = "4"
tracing = { version = "0.1", default-features = false, features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-tracy = { version = "0.10", optional = true }
winit = { version = "0.28", default-features = false }

[features]
default = ["x11"]
tracy = ["dep:tracing-tracy"]

# linux windowing backends
x11 = ["winit/x11"]
wayland = ["winit/wayland", "winit/wayland-dlopen"]

# rendering backends
wgpu = ["dep:ori-wgpu"]
