[package]
name = "ori-winit"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ori-core = { path = "../ori-core", version = "0.1.0-alpha.1" }

futures-lite = "1.13"

wgpu = { version = "0.17", optional = true }

[dependencies.winit] 
version = "0.28"
default-features = false
features = ["android-native-activity"]

[dependencies.tracing]
version = "0.1"
optional = true

[dependencies.tracing-subscriber]
version = "0.3" 
features = ["env-filter"]
optional = true

[features]
default = []
tracing = ["dep:tracing", "dep:tracing-subscriber"]
x11 = ["winit/x11"]
wayland = ["winit/wayland"]

wgpu = ["dep:wgpu"]
