name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build --verbose --no-default-features --features full

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2

    - name: Run tests
      run: cargo +nightly miri test --exclude ori --exclude ori-shell --verbose --workspace

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
 
    - name: Run clippy
      run: cargo clippy --verbose --no-default-features --features full

  rustfmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
 
    - name: Run rustfmt
      run: cargo fmt --check --verbose
