[package]
name = "ori-tiny-skia"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ori-core = { workspace = true }

tiny-skia = "0.11"
